### ISSUE TITLE
Custom range for puzzles

### ISSUE THREAD

**Issue by sooriravindra** [spothound/ThePawnsJourney#10]
Hello,

Love your work. Would it possible to add custom range for puzzles? For instance two drop-downs for start and end range where each option in the dropdown is an increment of 50?

Briefly looking at the code, I see that each puzzle range data is stored in a separate file and the data is populated upon request. Would it be possible to split the puzzle data into files of 50 elo range (puzzles_0_50.json, puzzles_50_100.json, etc) and load multiple files depending on user request? Just an idea, not sure if that is straightforward to implement.

**Comment by spothound** [comment]
Yeah, this is something I am working on. It is a bit tricky so far because of the way of how I store the puzzles but I will fix it asap. Thanks for the feedback!

**Comment by spothound** [comment]
this has ben solved, thanks for the feedback!
