### ISSUE TITLE
Editar Front End

### ISSUE THREAD

**Issue by Ch3ssMaster** [spothound/ThePawnsJourney#12]
Hola Francisco,

Me gustaría colaborar en este proyecto. Llevo tiempo planteándome hacer apps de ajedrez, y este puede ser un buen punto de partida. En principio me gustaría hacer un refactor de la interfaz: entre otras cosas, editar el logotipo (respetando el diseño), y cambiar el aspecto de la página de inicio. Antes de nada me gustaría saber si te parece bien.

Por otra parte, ¿es un hosting de pago?

**Comment by spothound** [comment]
Hola! pues si, me parece genial! Cualquier aporte es bienvenido :) y si tienes alguna duda sobre como funciona algo pregunta y con suerte te sepa explicar. Estoy ahora mismo un poco agobiado con otras cosas y no estoy pudiendo ponerme con esto demasiado pero en cuanto tenga algo de tiempo quiero empezar a meter cosillas interesantes.

Lo del hosting, no, es gratuito, esta desplegado en netlify.com con un tier gratuito. Ahora mismo no hay base de datos ni backend, todo el codigo está en el cliente. Pero me estoy planteando añadir una base de datos (también alguna gratis, tipo mongodb atlan) para guardar los puzzles y que sea mas fácil leerlos de ahí.

**Comment by spothound** [comment]
pd: el logo lo hice en un rato usando un modelo de AI, si creas otro mejor sería bienvenido no tienes que respetarlo mucho porque todavía no le he cogido cariño

**Comment by Ch3ssMaster** [comment]
Está bien 😄

Yo tengo hosting de pago, que incluye bbdd, y no me importaría hacerle sitio al proyecto.

Yo estoy también ahora algo liado, pero puedo ir empezando.

**Comment by spothound** [comment]
Me parece genial, pues si quieres nos ponemos en contacto y buscamos un hueco un dia para una llamada o algo y lo hablamos :)

**Comment by spothound** [comment]
I'll close this as we are already in contact
